language: node_js
node_js:
  - "8"
sudo: false
notifications:
  email: false
after_success:
  # Upload to coveralls, but don't _fail_ if coveralls is down.
  - cat coverage/lcov.info | node_modules/.bin/coveralls || echo "Coveralls upload failed" 